### ISSUE TITLE
Grav v1.1.2 - Admin v1.1.3 update error

### ISSUE THREAD

**Issue by fiddler1** [Edelan/grav-theme-gravi-k#8]
Just upgraded Grav to 1.1.2 and Twig_Error_Runtime error occurred.

"An exception has been thrown during the rendering of a template ("Declaration of Grav\Common\Page\Medium\ThumbnailImageMedium::html() should be compatible with Grav\Common\Page\Medium\Medium::html($title = NULL, $alt = NULL, $class = NULL, $id = NULL, $reset = true)") in "modular/gallery.html.twig" at line 33."

Downloaded a fresh copy of Grav + Admin. Installed gravi-k + plugins. 
The same error appears.

**Comment by Edelan** [comment]
Hi,
I fixed this error by making changes to the template. I think it's a problem with the method described in featherlight plugin, probably due to an update.

you can download and replace in `templates\modular`  the attached file by removing the .txt extension.

[gallery.html.twig.txt](https://github.com/Edelan/grav-theme-gravi-k/files/416538/gallery.html.twig.txt)

Before commit this change, can you tell me if it works for you.
Thanks.

**Comment by fiddler1** [comment]
Hi
Fixed. Works perfectly.
Thanks
